FROM checkr/flagr-ci as builder
WORKDIR /go/src/github.com/checkr/flagr
ADD . .
RUN make build-sync

FROM alpine:3.6
RUN apk add --no-cache libc6-compat ca-certificates
WORKDIR /go/src/github.com/checkr/flagr
VOLUME ["/data"]
COPY --from=builder /go/src/github.com/checkr/flagr/flagr-sync ./flagr-sync
CMD ./flagr-sync
